// This file is auto-generated by sync-version.ts
export const APP_VERSION = "0.1.0";
export const LATEST_COMMIT_HASH = "f413eb3";
export const CURRENT_BRANCH = "update_worker_name_to_custom-domains";
export const BUILD_TIME = "2026-03-22T22:12:12.265Z";
